create table customers (
  customer_id bigint generated by default as identity primary key,
  customer_number varchar(32) unique,
  first_name varchar(100) not null, last_name varchar(100) not null,
  email varchar(255) not null unique, phone varchar(50), password varchar(255) not null,
  status varchar(30) not null, role varchar(30) not null,
  created_at timestamp with time zone not null, updated_at timestamp with time zone not null
);
create table accounts (
  id bigint generated by default as identity primary key, customer_id bigint not null references customers(customer_id),
  account_number varchar(32) unique, type varchar(30) not null, currency varchar(3) not null,
  status varchar(30) not null, current_balance numeric(19,4) not null check(current_balance >= 0),
  available_balance numeric(19,4) not null check(available_balance >= 0), version bigint,
  created_at timestamp with time zone not null, updated_at timestamp with time zone not null
);
create table bank_transactions (
  id bigint generated by default as identity primary key, transaction_id varchar(36) not null unique, reference varchar(32) not null unique,
  type varchar(30) not null, status varchar(30) not null, amount numeric(19,4) not null check(amount > 0), currency varchar(3) not null,
  initiator_type varchar(100) not null, initiator_id varchar(255) not null, idempotency_key varchar(255) unique,
  request_fingerprint varchar(1000), reversal_of_id bigint references bank_transactions(id), created_at timestamp with time zone not null
);
create table ledger_entries (
  id bigint generated by default as identity primary key, transaction_id bigint not null references bank_transactions(id),
  account_id bigint references accounts(id), ledger_account varchar(100) not null, entry_type varchar(10) not null,
  amount numeric(19,4) not null check(amount > 0), currency varchar(3) not null
);
create table transaction_events (
  id bigint generated by default as identity primary key, transaction_id bigint not null references bank_transactions(id),
  event_type varchar(100) not null, payload varchar(4000) not null, created_at timestamp with time zone not null
);
create index idx_ledger_entries_account on ledger_entries(account_id, id);
create index idx_ledger_entries_transaction on ledger_entries(transaction_id, id);
